import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import Providers from "../provider/provider";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"]
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"]
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<Providers>
					<TooltipProvider>{children}</TooltipProvider>
					<Toaster richColors position="top-right" />
				</Providers>
			</body>
		</html>
	);
}
